// Copyright (c) 2026 Develeap
// SPDX-License-Identifier: MPL-2.0

package main

import (
	"fmt"
	"strings"

	"github.com/hyperping/terraform-provider-hyperping/pkg/migrate"
)

// generateScript generates an executable bash script for importing resources.
func (g *Generator) generateScript(data *ResourceData) string {
	var sb strings.Builder

	// Bash script header
	sb.WriteString("#!/bin/bash\n")
	sb.WriteString("# Generated by hyperping import-generator\n")
	sb.WriteString("# This script imports existing Hyperping resources into Terraform state\n")
	sb.WriteString("#\n")
	sb.WriteString("# Usage:\n")
	sb.WriteString("#   chmod +x import.sh\n")
	sb.WriteString("#   ./import.sh\n")
	sb.WriteString("#\n")
	sb.WriteString("# Requirements:\n")
	sb.WriteString("#   - Terraform must be installed\n")
	sb.WriteString("#   - You must be in a directory with Terraform configuration\n")
	sb.WriteString("#   - Resources must be defined in your .tf files\n")
	sb.WriteString("\n")
	sb.WriteString("set -e  # Exit on error\n")
	sb.WriteString("set -u  # Exit on undefined variable\n")
	sb.WriteString("\n")

	// Check for Terraform
	sb.WriteString("# Check if terraform is installed\n")
	sb.WriteString("if ! command -v terraform &> /dev/null; then\n")
	sb.WriteString("    echo \"Error: terraform command not found\"\n")
	sb.WriteString("    exit 1\n")
	sb.WriteString("fi\n")
	sb.WriteString("\n")

	// Initialize counters
	sb.WriteString("# Initialize counters\n")
	sb.WriteString("TOTAL=0\n")
	sb.WriteString("SUCCESS=0\n")
	sb.WriteString("FAILED=0\n")
	sb.WriteString("\n")

	// Import function
	sb.WriteString("# Import function with error handling\n")
	sb.WriteString("import_resource() {\n")
	sb.WriteString("    local resource_addr=\"$1\"\n")
	sb.WriteString("    local resource_id=\"$2\"\n")
	sb.WriteString("    \n")
	sb.WriteString("    TOTAL=$((TOTAL + 1))\n")
	sb.WriteString("    echo \"[$TOTAL] Importing $resource_addr...\"\n")
	sb.WriteString("    \n")
	sb.WriteString("    if terraform import \"$resource_addr\" \"$resource_id\"; then\n")
	sb.WriteString("        SUCCESS=$((SUCCESS + 1))\n")
	sb.WriteString("        echo \"  ✓ Success\"\n")
	sb.WriteString("    else\n")
	sb.WriteString("        FAILED=$((FAILED + 1))\n")
	sb.WriteString("        echo \"  ✗ Failed\"\n")
	sb.WriteString("    fi\n")
	sb.WriteString("    echo\n")
	sb.WriteString("}\n")
	sb.WriteString("\n")

	// Start importing
	sb.WriteString("echo \"Starting Terraform import...\"\n")
	sb.WriteString("echo\n")
	sb.WriteString("\n")

	// Generate import commands. UUIDs flow through migrate.QuoteShellUUID so
	// an attacker-influenced UUID-shaped value cannot smuggle command
	// substitution ($(...), ``...``) or statement chaining (;) into the
	// generated script.
	if len(data.Monitors) > 0 {
		sb.WriteString("# Monitors\n")
		for _, m := range data.Monitors {
			name := g.terraformName(m.Name)
			addr := fmt.Sprintf("hyperping_monitor.%s", name)
			fmt.Fprintf(&sb, "import_resource %q %s\n", addr, migrate.QuoteShellUUID(m.UUID))
		}
		sb.WriteString("\n")
	}

	if len(data.Healthchecks) > 0 {
		sb.WriteString("# Healthchecks\n")
		for _, h := range data.Healthchecks {
			name := g.terraformName(h.Name)
			addr := fmt.Sprintf("hyperping_healthcheck.%s", name)
			fmt.Fprintf(&sb, "import_resource %q %s\n", addr, migrate.QuoteShellUUID(h.UUID))
		}
		sb.WriteString("\n")
	}

	if len(data.StatusPages) > 0 {
		sb.WriteString("# Status Pages\n")
		for _, sp := range data.StatusPages {
			name := g.terraformName(sp.Name)
			addr := fmt.Sprintf("hyperping_statuspage.%s", name)
			fmt.Fprintf(&sb, "import_resource %q %s\n", addr, migrate.QuoteShellUUID(sp.UUID))
		}
		sb.WriteString("\n")
	}

	if len(data.Incidents) > 0 {
		sb.WriteString("# Incidents\n")
		for _, i := range data.Incidents {
			name := g.terraformName(i.Title.En)
			addr := fmt.Sprintf("hyperping_incident.%s", name)
			fmt.Fprintf(&sb, "import_resource %q %s\n", addr, migrate.QuoteShellUUID(i.UUID))
		}
		sb.WriteString("\n")
	}

	if len(data.Maintenance) > 0 {
		sb.WriteString("# Maintenance Windows\n")
		for _, m := range data.Maintenance {
			titleText := m.Title.En
			if titleText == "" {
				titleText = m.Name
			}
			name := g.terraformName(titleText)
			addr := fmt.Sprintf("hyperping_maintenance.%s", name)
			fmt.Fprintf(&sb, "import_resource %q %s\n", addr, migrate.QuoteShellUUID(m.UUID))
		}
		sb.WriteString("\n")
	}

	if len(data.Outages) > 0 {
		sb.WriteString("# Outages\n")
		for _, o := range data.Outages {
			name := g.terraformName(o.Monitor.Name)
			addr := fmt.Sprintf("hyperping_outage.%s", name)
			fmt.Fprintf(&sb, "import_resource %q %s\n", addr, migrate.QuoteShellUUID(o.UUID))
		}
		sb.WriteString("\n")
	}

	// Summary
	sb.WriteString("# Print summary\n")
	sb.WriteString("echo \"=\"\n")
	sb.WriteString("echo \"Import Summary\"\n")
	sb.WriteString("echo \"=\"\n")
	sb.WriteString("echo \"Total:   $TOTAL\"\n")
	sb.WriteString("echo \"Success: $SUCCESS\"\n")
	sb.WriteString("echo \"Failed:  $FAILED\"\n")
	sb.WriteString("\n")
	sb.WriteString("if [ $FAILED -gt 0 ]; then\n")
	sb.WriteString("    echo\n")
	sb.WriteString("    echo \"Some imports failed. Please check the errors above.\"\n")
	sb.WriteString("    exit 1\n")
	sb.WriteString("fi\n")
	sb.WriteString("\n")
	sb.WriteString("echo\n")
	sb.WriteString("echo \"All imports completed successfully!\"\n")

	return sb.String()
}
